package entidades;
// Generated 14/07/2019 06:45:13 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Vacuna generated by hbm2java
 */
public class Vacuna  implements java.io.Serializable {


     private int idVacuna;
     private Date fecha;
     private String enfermedad;
     private Date fechaProxima;

    public Vacuna() {
    }

    public Vacuna(int idVacuna, Date fecha, String enfermedad, Date fechaProxima) {
       this.idVacuna = idVacuna;
       this.fecha = fecha;
       this.enfermedad = enfermedad;
       this.fechaProxima = fechaProxima;
    }
   
    public int getIdVacuna() {
        return this.idVacuna;
    }
    
    public void setIdVacuna(int idVacuna) {
        this.idVacuna = idVacuna;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getEnfermedad() {
        return this.enfermedad;
    }
    
    public void setEnfermedad(String enfermedad) {
        this.enfermedad = enfermedad;
    }
    public Date getFechaProxima() {
        return this.fechaProxima;
    }
    
    public void setFechaProxima(Date fechaProxima) {
        this.fechaProxima = fechaProxima;
    }




}


